# Generated by Django 4.2.14 on 2024-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
