# Generated by Django 4.2.14 on 2024-08-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_lesson_lesson_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_resources",
                to="courses.course",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("learning_material", "Learning Material"),
                    ("additional_resource", "Additional Resource"),
                    ("course_cover_picture", "Course Cover Picture"),
                    ("user_profile_picture", "User Profile Picture"),
                    ("status_update", "Status Update"),
                ],
                max_length=20,
            ),
        ),
    ]
