# Generated by Django 4.2.14 on 2024-08-23 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("status_updates", "0001_initial"),
        ("courses", "0004_alter_resource_course_alter_resource_resource_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="status_update",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_update_resource",
                to="status_updates.statusupdate",
            ),
        ),
    ]
