# Generated by Django 4.2.14 on 2024-08-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0005_resource_status_update"),
        ("status_updates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusupdate",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_update_course",
                to="courses.course",
            ),
        ),
    ]
